"""Unit-root and cointegration testing, implemented from the regressions up.

There is no statsmodels dependency here. The Augmented Dickey-Fuller
regression, its lag selection, the Engle-Granger two-step procedure and the
Ornstein-Uhlenbeck half-life are all built directly, which means the critical
values have to be dealt with honestly rather than imported.

Two independent sources of critical values are kept, and they are compared
against each other by ``scripts/validate.py``:

1. **MacKinnon (2010) response surfaces** — the published finite-sample
   coefficients, used for the accept/reject decision. ``tau(T) = tau_inf +
   b1/T + b2/T^2 + b3/T^3``.
2. **This project's own Monte Carlo table** — ``tables/df_quantiles.csv``,
   generated by ``scripts/tabulate_df.py`` from simulated random walks and
   used to turn a statistic into a p-value by interpolation.

If the implementation of the ADF regression were wrong, the simulated table
would disagree with the published one, and the validation gate would fail.

The distinction that matters for cointegration testing: when the tested series
is a *residual* from an estimated cointegrating regression rather than observed
data, the null distribution shifts left, because the regression has already
minimised the residual variance. That is what ``n_series`` selects — 1 for a
plain unit-root test on observed data, 2 for a residual from a two-variable
cointegrating regression.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

_TABLE_DIR = Path(__file__).resolve().parent / "tables"

# MacKinnon (2010), "Critical Values for Cointegration Tests", Table 2.
# Keyed by (deterministic terms in the regression, number of series).
#   "n"  no constant   "c"  constant   "ct"  constant and trend
# Value is {significance level: (tau_inf, b1, b2, b3)}.
MACKINNON: dict[tuple[str, int], dict[float, tuple[float, float, float, float]]] = {
    ("n", 1): {
        0.01: (-2.56574, -2.2358, -3.627, 0.0),
        0.05: (-1.94100, -0.2686, -3.365, 31.223),
        0.10: (-1.61682, 0.2656, -2.714, 25.364),
    },
    ("c", 1): {
        0.01: (-3.43035, -6.5393, -16.786, -79.433),
        0.05: (-2.86154, -2.8903, -4.234, -40.040),
        0.10: (-2.56677, -1.5384, -2.809, 0.0),
    },
    ("ct", 1): {
        0.01: (-3.95877, -9.0531, -28.428, -134.155),
        0.05: (-3.41049, -4.3904, -9.036, -45.374),
        0.10: (-3.12705, -2.5856, -3.925, -22.380),
    },
    ("c", 2): {
        0.01: (-3.89644, -10.9519, -33.527, 0.0),
        0.05: (-3.33613, -6.1101, -6.823, 0.0),
        0.10: (-3.04445, -4.2412, -2.720, 0.0),
    },
    ("ct", 2): {
        0.01: (-4.32762, -15.4387, -35.679, 0.0),
        0.05: (-3.78034, -9.5106, -12.074, 0.0),
        0.10: (-3.49220, -7.0815, -7.538, 0.0),
    },
}


def mackinnon_crit(
    regression: str = "c",
    n_series: int = 1,
    nobs: int = 1_000_000,
) -> dict[float, float]:
    """Finite-sample critical values at the 1/5/10% levels.

    ``nobs`` left at its default returns the asymptotic values.
    """
    key = (regression, n_series)
    if key not in MACKINNON:
        raise ValueError(
            f"no published critical values for regression={regression!r}, "
            f"n_series={n_series}; available: {sorted(MACKINNON)}"
        )
    t = float(nobs)
    return {
        level: inf + b1 / t + b2 / t**2 + b3 / t**3
        for level, (inf, b1, b2, b3) in MACKINNON[key].items()
    }


# --------------------------------------------------------------------------
# The ADF regression
# --------------------------------------------------------------------------


@dataclass
class ADFResult:
    """Outcome of an Augmented Dickey-Fuller test."""

    stat: float                 # t-statistic on the lagged level
    pvalue: float               # from this project's simulated null
    lag: int                    # lags of the differenced series that were used
    nobs: int                   # observations the regression actually used
    crit: dict[float, float]    # MacKinnon finite-sample critical values
    regression: str
    n_series: int

    def rejects(self, level: float = 0.05) -> bool:
        """True if the unit-root null is rejected at ``level``.

        Uses the MacKinnon critical value, not the simulated p-value, so the
        headline decision rests on the published table.
        """
        return self.stat < self.crit[level]


def _design(y: np.ndarray, lag: int, regression: str, start: int) -> tuple[np.ndarray, np.ndarray]:
    """Build the ADF design matrix, first column = the lagged level.

    ``start`` fixes the first usable observation across every candidate lag
    so that lag selection compares models on an identical sample.
    """
    dy = np.diff(y)
    n = len(dy)
    resp = dy[start:]
    cols = [y[start:-1]]                        # y_{t-1}
    for i in range(1, lag + 1):
        cols.append(dy[start - i : n - i])      # Delta y_{t-i}
    if regression in ("c", "ct"):
        cols.append(np.ones(len(resp)))
    if regression == "ct":
        cols.append(np.arange(len(resp), dtype=float))
    return np.column_stack(cols), resp


def _fit(X: np.ndarray, resp: np.ndarray) -> tuple[float, float, float]:
    """OLS. Returns the t-statistic on column 0, the SSR and the dof."""
    xtx = X.T @ X
    xtx_inv = np.linalg.pinv(xtx)
    beta = xtx_inv @ (X.T @ resp)
    resid = resp - X @ beta
    ssr = float(resid @ resid)
    dof = len(resp) - X.shape[1]
    if dof <= 0 or ssr <= 0:
        return np.nan, ssr, dof
    sigma2 = ssr / dof
    se = np.sqrt(sigma2 * xtx_inv[0, 0])
    if not np.isfinite(se) or se == 0:
        return np.nan, ssr, dof
    return float(beta[0] / se), ssr, dof


def schwert_maxlag(nobs: int) -> int:
    """Schwert's rule of thumb for the maximum lag, ``12*(T/100)^(1/4)``."""
    return int(np.ceil(12.0 * (nobs / 100.0) ** 0.25))


def adf_test(
    y,
    max_lag: int | None = None,
    regression: str = "c",
    n_series: int = 1,
    autolag: bool = True,
    crit_regression: str | None = None,
) -> ADFResult:
    """Augmented Dickey-Fuller test for a unit root in ``y``.

    Fits ``dy_t = gamma*y_{t-1} + sum_i delta_i dy_{t-i} + deterministic + e_t``
    and reports the t-statistic on ``gamma``. A large negative statistic is
    evidence against the unit root, i.e. evidence *for* stationarity.

    Lag order is chosen by AIC over ``0..max_lag`` on a common sample. Set
    ``autolag=False`` to force ``max_lag`` exactly.

    ``regression`` controls the deterministic terms in the ADF regression
    itself. ``crit_regression`` selects which null distribution to score
    against, and defaults to ``regression``. The two differ in exactly one
    place: an Engle-Granger residual is tested with no constant of its own
    (``regression="n"``) but must be judged against the distribution for a
    cointegrating regression that *did* include one (``crit_regression="c"``).
    """
    crit_regression = crit_regression or regression
    y = np.asarray(y, dtype=float)
    y = y[np.isfinite(y)]
    if len(y) < 20:
        raise ValueError(f"need at least 20 observations, got {len(y)}")

    if max_lag is None:
        max_lag = schwert_maxlag(len(y))
    # Leave enough rows to estimate the largest candidate model.
    max_lag = int(min(max_lag, (len(y) - 10) // 3))
    max_lag = max(max_lag, 0)

    start = max_lag
    best = (np.inf, 0, np.nan, 0)
    lags = range(max_lag + 1) if autolag else (max_lag,)
    for lag in lags:
        X, resp = _design(y, lag, regression, start)
        stat, ssr, dof = _fit(X, resp)
        if not np.isfinite(stat):
            continue
        nobs = len(resp)
        aic = nobs * np.log(ssr / nobs) + 2.0 * X.shape[1]
        if aic < best[0]:
            best = (aic, lag, stat, nobs)

    _, lag, stat, nobs = best
    if not np.isfinite(stat):
        raise ValueError("ADF regression was degenerate for this series")

    return ADFResult(
        stat=stat,
        pvalue=adf_pvalue(stat, regression=crit_regression, n_series=n_series),
        lag=lag,
        nobs=nobs,
        crit=mackinnon_crit(crit_regression, n_series, nobs),
        regression=regression,
        n_series=n_series,
    )


# --------------------------------------------------------------------------
# p-values from the project's own simulated null distribution
# --------------------------------------------------------------------------


@lru_cache(maxsize=None)
def _quantile_table() -> pd.DataFrame:
    path = _TABLE_DIR / "df_quantiles.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"simulated null distribution missing: {path}\n"
            "Regenerate it with: python scripts/tabulate_df.py"
        )
    return pd.read_csv(path)


def adf_pvalue(stat: float, regression: str = "c", n_series: int = 1) -> float:
    """Interpolate a p-value from the simulated Dickey-Fuller distribution.

    The table stores quantiles of the statistic under the unit-root null, so
    the p-value of an observed statistic is the fraction of the null that lies
    below it — read off by linear interpolation and clipped to the tabulated
    range, since nothing outside it was actually simulated.
    """
    tab = _quantile_table()
    sel = tab[(tab["regression"] == regression) & (tab["n_series"] == n_series)]
    if sel.empty:
        return np.nan
    sel = sel.sort_values("quantile")
    return float(
        np.interp(stat, sel["stat"].to_numpy(), sel["quantile"].to_numpy())
    )


def simulate_df_stats(
    nobs: int,
    n_reps: int,
    regression: str = "c",
    n_series: int = 1,
    seed: int = 0,
    chunk: int = 2_000,
) -> np.ndarray:
    """Simulate the Dickey-Fuller statistic under the unit-root null.

    ``n_series=1`` tests a random walk directly. ``n_series=2`` first regresses
    one random walk on an *independent* other one (with a constant) and tests
    the residual, which is the Engle-Granger setting: the two series are not
    cointegrated by construction, so anything the test rejects here is a false
    positive.

    Returns the statistics, unsorted. Vectorized over replications; the
    zero-lag statistic is used, whose asymptotic distribution is the same as
    the augmented one under the null.
    """
    rng = np.random.default_rng(seed)
    out = np.empty(n_reps, dtype=float)
    done = 0

    while done < n_reps:
        m = min(chunk, n_reps - done)
        walks = np.cumsum(rng.standard_normal((nobs, m)), axis=0)

        if n_series == 1:
            series = walks
            det = regression
        elif n_series == 2:
            if regression != "c":
                raise ValueError("only regression='c' is tabulated for n_series=2")
            other = np.cumsum(rng.standard_normal((nobs, m)), axis=0)
            # Cointegrating regression of each walk on [1, other]; keep residuals.
            xm = other - other.mean(axis=0)
            ym = walks - walks.mean(axis=0)
            beta = (xm * ym).sum(axis=0) / (xm * xm).sum(axis=0)
            series = ym - beta * xm
            det = "n"            # residuals carry no deterministic term of their own
        else:
            raise ValueError("n_series must be 1 or 2")

        out[done : done + m] = _df_stat_columns(series, regression=det)
        done += m

    return out


def _deterministic(n: int, regression: str) -> np.ndarray | None:
    """The deterministic regressor block for ``n`` observations."""
    if regression == "n":
        return None
    ones = np.ones((n, 1))
    if regression == "c":
        return ones
    if regression == "ct":
        return np.column_stack([ones, np.arange(n, dtype=float)])
    raise ValueError("regression must be 'n', 'c' or 'ct'")


def _df_stat_columns(series: np.ndarray, regression: str) -> np.ndarray:
    """Zero-lag Dickey-Fuller t-statistic for every column of ``series``.

    Deterministic terms are removed by Frisch-Waugh rather than by stacking
    them into the design: projecting them out of both the lagged level and the
    difference leaves the t-statistic on the level unchanged, and does it for
    every replication at once with a single projection.
    """
    lev = series[:-1]
    dif = np.diff(series, axis=0)
    n = lev.shape[0]

    det = _deterministic(n, regression)
    if det is None:
        x, d, k = lev, dif, 1
    else:
        proj = det @ np.linalg.pinv(det)
        x = lev - proj @ lev
        d = dif - proj @ dif
        k = 1 + det.shape[1]

    sxx = (x * x).sum(axis=0)
    gamma = (x * d).sum(axis=0) / sxx
    resid = d - gamma * x
    sigma2 = (resid * resid).sum(axis=0) / (n - k)
    return gamma / np.sqrt(sigma2 / sxx)


# --------------------------------------------------------------------------
# Engle-Granger and the spread
# --------------------------------------------------------------------------


@dataclass
class CointResult:
    """Outcome of an Engle-Granger cointegration test on a pair."""

    stat: float
    pvalue: float
    crit: dict[float, float]
    alpha: float                # intercept of the cointegrating regression
    beta: float                 # hedge ratio: 1 unit of y against beta of x
    spread: pd.Series           # y - alpha - beta*x
    half_life: float            # days for a shock to the spread to halve
    lag: int
    nobs: int
    swapped: bool = False       # True if the second input ended up as the LHS

    def rejects(self, level: float = 0.05) -> bool:
        """True if no-cointegration is rejected at ``level``."""
        return self.stat < self.crit[level]


def hedge_ratio(y, x) -> tuple[float, float]:
    """OLS of ``y`` on ``[1, x]``. Returns ``(alpha, beta)``.

    ``beta`` is the number of units of ``x`` to hold against one unit of ``y``.
    Note this is not symmetric — regressing x on y gives a different pair, and
    ``engle_granger`` deals with that explicitly.
    """
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)
    X = np.column_stack([np.ones_like(x), x])
    beta, *_ = np.linalg.lstsq(X, y, rcond=None)
    return float(beta[0]), float(beta[1])


def ou_half_life(spread) -> float:
    """Half-life of mean reversion, from the discrete Ornstein-Uhlenbeck fit.

    Regresses ``ds_t = a + b*s_{t-1} + e_t``, which is an AR(1) in disguise
    with ``phi = 1 + b``. A shock then decays as ``phi^t``, so it halves at
    ``t = ln(2) / -ln(phi)``.

    The approximation ``ln(2)/-b`` is what most implementations use, and it is
    the first-order expansion of the above. It is fine for slow reversion and
    visibly wrong for fast: at ``phi = 0.9`` it says 6.93 days against the true
    6.58, a 5% overstatement, and the error grows as ``phi`` falls. Since the
    half-life is used as a *filter threshold* here, taking the exact form
    costs nothing and removes a bias that would push borderline pairs across
    the cut.

    Returns ``inf`` when nothing pulls the spread back (``b >= 0``) and ``0``
    when the fit overshoots the mean every step (``phi <= 0``), which is not
    mean reversion but alternating noise.
    """
    s = np.asarray(spread, dtype=float)
    s = s[np.isfinite(s)]
    if len(s) < 10:
        return np.inf
    lev = s[:-1]
    dif = np.diff(s)
    X = np.column_stack([np.ones_like(lev), lev])
    coef, *_ = np.linalg.lstsq(X, dif, rcond=None)
    phi = 1.0 + float(coef[1])
    if phi >= 1.0:
        return np.inf
    if phi <= 0.0:
        return 0.0
    return float(np.log(2.0) / -np.log(phi))


def engle_granger(
    y: pd.Series,
    x: pd.Series,
    max_lag: int | None = None,
    regression: str = "c",
) -> CointResult:
    """Engle-Granger two-step cointegration test on a pair of price series.

    Step 1 estimates the cointegrating regression ``y = alpha + beta*x + s``.
    Step 2 tests the residual ``s`` for a unit root, with no constant (the
    residual is mean zero by construction) and against the ``n_series=2``
    critical values, which account for ``beta`` having been estimated.

    Both orderings are tried and the more negative statistic is returned. This
    is deliberate and is a *known* source of selection bias — it is one more
    test per pair, and ``pairs.screen_universe`` accounts for it when it counts
    expected false positives.
    """
    joined = pd.concat([y, x], axis=1).dropna()
    if len(joined) < 30:
        raise ValueError(f"need at least 30 overlapping observations, got {len(joined)}")
    a, b = joined.iloc[:, 0], joined.iloc[:, 1]

    best: CointResult | None = None
    for swapped, (lhs, rhs) in enumerate(((a, b), (b, a))):
        alpha, beta = hedge_ratio(lhs, rhs)
        resid = lhs - alpha - beta * rhs
        adf = adf_test(
            resid.to_numpy(),
            max_lag=max_lag,
            regression="n",
            n_series=2,
            autolag=True,
            crit_regression=regression,
        )
        cand = CointResult(
            stat=adf.stat,
            pvalue=adf.pvalue,
            crit=adf.crit,
            alpha=alpha,
            beta=beta,
            spread=pd.Series(resid.to_numpy(), index=joined.index, name="spread"),
            half_life=ou_half_life(resid),
            lag=adf.lag,
            nobs=adf.nobs,
            swapped=bool(swapped),
        )
        if best is None or cand.stat < best.stat:
            best = cand

    assert best is not None
    return best
